theme: jekyll-theme-minimal
title: [Vassili Kurman]
description: [I am a software engineer interested in development of Android and Web Apps using Java, C#, Python and JavaScript]
show_downloads: false
is_project_page: false
is_user_page: true
owner_url: https://github.com/VassiliKurman
